FROM ubuntu:trusty

# Install utilities
RUN apt-get update --fix-missing && apt-get -y upgrade &&\
apt-get install -y build-essential automake libcurl4-openssl-dev ocl-icd-opencl-dev

WORKDIR /

# Copy files
COPY /compat/ /compat/
COPY autogen.sh /
COPY bitops.h /
COPY compat.h /
COPY configure.ac /
COPY cpu-miner.c /
COPY elist.h /
COPY gpu.c /
COPY gpu.h /
COPY helper.h /
COPY Makefile.am /
COPY miner.h /
COPY minerd.1 /
COPY reciprocal_div64.h /
COPY util.c /
COPY wild_keccak.cl /
COPY wild_keccak_multi.cl /
COPY wildkeccak.c /
RUN sh autogen.sh
RUN ./configure CFLAGS="-O3 -march=native"
RUN make
